server:
  port: 7000
eureka:
  client:
    #注册进eureka
    register-with-eureka: true
    #是否从eurekaServer中抓取已有的注册信息，默认为true。单点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 注册中心服务接口
      defaultZone: http://localhost:7001/eureka
logging:
  level:
    com.chq.project.cloud : debug
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: system
          uri: lb://system
          predicates:
           - Path=/system/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**