server:
  port: 7002
eureka:
  client:
    #注册进eureka
    register-with-eureka: true
    #是否从eurekaServer中抓取已有的注册信息，默认为true。单点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 注册中心服务接口
      defaultZone: http://localhost:7001/eureka
logging:
  level:
    com.chq.project.cloud : debug
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chq00788/spring-cloud-config.git
          search-paths:
            - spring-cloud-config
      label: master